name: pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v6.0.1

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install veccs
        run: |
          uv sync --locked --dev

      - name: Install stubs for mypy
        run: |
          uv pip install types-Deprecated

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
